[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "cd site && ./hoor && cd .. && yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "cd site && ./hoor && cd .. && yarn hugo"
