baseurl = "https://feedium-production.netlify.com"
title = "فیدیوم"
layoutDir = "layouts"
contentdir = "content"
assetDir = "static"
publishdir = "dist"
metaDataFormat = "yaml"
buildDrafts = false
buildFuture = true
canonifyurls = true
pygmentsUseClasses = true
relativeURLs = true
uglyURLs = false
verbose = false
log = false
pluralizelisttitles = false
preserveTaxonomyNames = true
footnotereturnlinkcontents = "⇆"
disableHugoGeneratorInject = true
enableRobotsTXT = true
paginatePath = "page"
enableGitInfo = true
rssLimit = 100
optimize = true
shamsiDateFormat = "d MMM ماه yyyy"
DefaultContentLanguage = "fa"
minify = true
[params]
LatinName = "Feedium"
color = "darkBlue"
copyright = "کلیه مطالب این وبلاگ براساس گواهی کریتیو کامنز ۴.۰ (BY-NC-SA) منتشر می‌شود."
cover = "/uploads/cover-default.png"
description = "Params description"
fullPersianName = "فیدیوم - نگاهی متفاوت به خبرها"
htmlDirection = "rtl"
languageCode = "fa-IR"
pageCover = "/uploads/page-default.png"
paginate = 6
tags = "Feedium, فیدیوم"

[params.author]
email = "info@feedium.net"
name = "Feedium"

[params.link]
comment = "false"
disqusUser = "hilnu"
facebooUser = "pagename"
facebook = "true"
github = "true"
githubUser = "kevinmiston"
instagram = "true"
instagramUser = "pagename"
rss = "true"
telegram = "true"
telegramUser = "feedium"
twitter = "true"
twitterUser = "feedium"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[permalinks]
posts = "/posts/:title/"
feed ="/feed/:year/:month/:day"

[taxonomies]
author = "author"
category = "section"
tag = "topic"

[mediaTypes]

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats]

[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[outputs]
home = ["HTML", "RSS", "AMP", "HEADERS"]
page = ["HTML", "AMP"]
section = ["HTML", "AMP"]
taxonomy = ["HTML", "AMP"]
taxonomyTerm = ["HTML", "AMP"]